name: Compile and Release

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build - ${{ matrix.platform.release_for }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            target: x86_64-unknown-linux-musl
            bin: rusty-timetracker
            name: rusty-timetracker-Linux-x86_64
          - release_for: Windows-x86_64
            target: x86_64-pc-windows-gnu
            bin: rusty-timetracker.exe
            name: rusty-timetracker-Windows-x86_64.exe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Update Rust
        run: rustup update
      - name: Install dependencies
        run: rustup target add ${{ matrix.platform.target }}
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.platform.target }}
          EXTRA_FILES: "README.md LICENSE"
          UPLOAD_MODE: none
      - name: Upload ${{ matrix.platform.release_for }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
#      - name: Publish GitHub release
#        uses: softprops/action-gh-release@v1
#        with:
#          draft: true
#          files: "timetracker-*"
#          body_path: Changes.md
#        env:
#          GITHUB_TOKEN: ${{ secrets.PAT }}
#        if: startsWith( github.ref, 'refs/tags/v' )
