name: Compile and Release

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: rustup update stable
    - name: Compile for Linux
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=aarch64-unknown-linux-gnu
    - name: Compile for Windows
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=x86_64-pc-windows-gnu
    - name: Compile for MacOs
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=aarch64-apple-darwin
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: timetracker
        path: ./target/aarch64-unknown-linux-gnu/release/timetracker
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: timetracker
        path: ./target/x86_64-pc-windows-gnu/release/timetracker
    - name: Upload MacOs artifact
      uses: actions/upload-artifact@v3
      with:
        name: timetracker
        path: ./target/aarch64-apple-darwin/release/timetracker
