name: Compile and Release

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: rustup update stable
    - name: Install cross-compilation tools
      uses: taiki-e/setup-cross-toolchain-action@v1
      with:
        target: aarch64-unknown-linux-gnu
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: timetracker
        path: ./target/aarch64-unknown-linux-gnu/release/timetracker
