name: Compile and Release

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: rusty-timetracker
            name: rusty-timetracker-Linux-x86_64

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: rusty-timetracker.exe
            name: rusty-timetracker-Windows-x86_64.exe

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: rusty-timetracker
            name: rusty-timetracker-Darwin-x86_64

    #          - release_for: macOS-aarch64
    #            os: macOS-latest
    #            target: aarch64-apple-darwin
    #            bin: rusty-timetracker
    #            name: rusty-timetracker-Darwin-aarch64.tar.gz

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.name }}
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
#      - name: Generate SHA-256
#        if: matrix.platform.os == 'macOS-latest'
#        run: shasum -a 256 ${{ matrix.platform.name }}
#      - name: Publish GitHub release
#        uses: softprops/action-gh-release@v1
#        with:
#          draft: true
#          files: "timetracker-*"
#          body_path: Changes.md
#        env:
#          GITHUB_TOKEN: ${{ secrets.PAT }}
#        if: startsWith( github.ref, 'refs/tags/v' )
